[en]
  title = "Lets Filipino"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

# [ph]
#   title = "Lets Filipino"
#   languageName = "Pinoy"
#   weight = 2
#   languagedir = "ltr"
#   contentdir = "content/ph"
