[en]
  title = "Hugo Zzo Theme"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[ph]
  title = "Hugo Zzo Theme"
  languageName = "Pinoy"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/ph"
