[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1


[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

# [[main]]
#   identifier = "presentation"
#   name = "Tools"
#   url = "presentation"
#   weight = 3

# [[main]]
#   identifier = "gallery"
#   name = "Gallery"
#   url = "gallery"
#   weight = 4
    
# [[main]]
#   parent = "gallery"
#   name = "Cartoon"
#   url = "gallery/cartoon"

# [[main]]
#   parent = "gallery"
#   name = "Photo"
#   url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 5

[[main]]
  parent = "posts"
  identifier = "categories"
  name = "Categories"
  url = "categories"
  weight = 5

[[main]]
  parent = "posts"
  identifier = "series"
  name = "Series"
  url = "series"
  weight = 5

[[main]]
  parent = "posts"
  identifier = "tags"
  name = "Tags"
  url = "tags"
  weight = 5

# [[main]]
#   identifier = "showcase"
#   name = "Showcase"
#   url = "showcase"
#   weight = 6

# [[main]]
#   identifier = "publication"
#   name = "Pub"
#   url = "publication"
#   weight = 7


# Social Media
[[main]]
  identifier = "social"
  name = "Social"
  weight = 6

[[main]]
  parent = "social"
  name = "YouTube"
  url = "https://www.youtube.com/channel/UCd2GYeVAsuDE-qUdxtUEs8A"

[[main]]
  parent = "social"
  name = "FaceBook"
  url = "https://www.facebook.com/letsfilipino"

[[main]]
  parent = "social"
  name = "Instagram"
  url = "https://www.instagram.com/papajedder/"


